# Generated by Django 6.0.4 on 2026-05-11 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("place", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="place",
            name="category",
        ),
        migrations.AlterField(
            model_name="place",
            name="image",
            field=models.ImageField(upload_to="place_images"),
        ),
    ]
