# Generated by Django 6.0.4 on 2026-05-13 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("place", "0002_remove_place_category_alter_place_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="image",
            field=models.ImageField(upload_to="placeimages"),
        ),
    ]
