# Generated by Django 6.0.4 on 2026-05-07 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipe_name', models.CharField(max_length=500)),
                ('receipe_description', models.TextField(max_length=500)),
                ('reciepe_image', models.ImageField(upload_to='')),
            ],
        ),
    ]
