# Generated by Django 6.0.4 on 2026-05-07 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipe',
            old_name='reciepe_image',
            new_name='receipe_image',
        ),
    ]
